### ISSUE TITLE
Website dropdown menus

### ISSUE THREAD

**Issue by PQAdvantage** [theQRL/theqrl.org#73]
*Apologies again for posting in the wrong place; proposed dropdowns below, please feel free to adjust as you all see fit, but IMHO something closer to this would be very helpful.

About
--> FAQ (that incorporates What is QRL?)
--> Team
--> Roadmap
--> Community (link to part of page with links for Discord, Reddit, Twitter, Facebook)
--> Conferences
--> Whitepapers
--> Security (link to general info on audits, XMSS etc.)
--> Academia
--> In the Press
--> QRL Foundation
Get Started
--> Buy & Sell QRL (link to Bittrex)
--> Wallets (link to web wallet etc.)
--> Mining (link to quick start guide)
--> Nodes (link to guide)
Developers --> keep the same dropdowns
Partners [?]
Updates
--> Announcements (links to latest Medium post)
--> QRL Improvement Proposals (QIPs)
Resources
--> Explorer
--> Github
--> NIST (link to https://csrc.nist.gov/)
--> Quantum Computing Report (link to https://quantumcomputingreport.com/)
--> Anything else?
Contact Us
--> General
--> Media
-->Partners
--> Exchanges
--> Support

**Comment by jackalyst** [comment]
Thank you for making an issue on github.

So right now we have

- Getting Started
- Developers
-> Github
-> API
-> API: Wallet
-> API: Explorer
-> Documentation
-> Contributors
- Academia
-> Citations
-> Cryptography
-> Seminal Papers
-> Further reading (will make it to a future PR)
- Announcements
- Protocol Updates

I'm personally wary about putting more top level menu items here due to the risk reducing the effectiveness of others. See: "if everything is a priority, nothing is a priority"

The other thing is that I always want to make sure the items are indirectly making a statement about our project: Effectively that we're a decentralized community driven, open source base protocol layer that's highly respected, easy to use, develop on, highly secure and has a ton of research to back it up.

**Further thoughts and considerations**
- Being immediately descriptive presents an immediate problem with 'about' as a top level item, but with regards to some sub sections I can see a community section being highlighted, maybe even a top level row, sometimes reserved for 'communications' (social media, community, contact) - but I can see qips fitting up there too. While we're putting the team back, at least temporarily, they're going under under developers. 
- I've heard from a few people now that 'Protocol Updates' is also a bit confusing. We're trying to communicate here that 1) The QRL isn't on a rolling release cycle (like Arch) and instead a standard release cycle (like Fedora), 2) QIPs with community voting guides this process, 3) That we'd like to be seen as a protocol, and 4) This is where updates and upcoming features are seen. The main issue I think is with (4), where people expect the word 'roadmap'. Ultimately, this could be too many things to communicate in one menu item and it might be worth being broken up or changed back to 'Roadmap'. Roadmap actually still seems applicable because QIPs can be seen as 'potential' things on the roadmap, while voted in QIPs can get closer to being in the next release cycle.
- 'In the press' and 'media' don't fit with the statement "a decentralized community driven, open source base protocol layer that's highly respected, easy to use, develop on, highly secure and has a ton of research to back it up.", it may be possible to have a community driven site for this.
- Great suggestion on having 'Getting Started' have a dropdown
- Security seems good... maybe it's own heading or under academia?
- For resources, we already have github under development (which is where you'd expect it... though it can be an 'social' icon in the header. NIST and Quantum Computing report would be good additions for 'further reading' that we just added to the academia section.

The above would result in two menus

**Top community/social 'bar'**
- Community social icons from the bottom of the page (but smaller)
- Active QIPS
- email (support@theqrl.org)

**Normal menu**
- Getting Started
-> Buy & Sell QRL (link to Bittrex)
-> Wallets (link to web wallet etc.)
-> Mining (link to quick start guide)
-> Nodes (link to guide)
- Developers
-> Github
-> API
-> API: Wallet
-> API: Explorer
-> Documentation
-> Contributors
-> Team
- Academia
-> Citations
-> Cryptography & Security
-> Audits
-> Seminal Papers
-> Further reading
-> Whitepapers
- Announcements
- Roadmap
-> Protocol release cycle
-> Features in next protocol release
-> QRL Improvement Proposals (QIPs)

**Comment by PQAdvantage** [comment]
Jack, you always astonish me at how well you synthesize feedback and come up with an improved output.  The newly proposed dropdowns look great to me and I think would represent a significant improvement.  Couple quick thoughts:  1) I think the proposed Academia dropdown is broader and might warrant a different title like say 'Background' or 'Deep Dive' or something like that; 2) I'm not hung up on Roadmap, think it could be Updates perhaps and announcements goes under it or whatever other generic term that works; 3) I might suggest 'External Resources' instead of 'Further Reading' but I do like the idea of having something like that readily accessible and FWIW my experience is those kinds of external links to reputable websites _do_ seem to help SEO (though I know we have community experts who may disagree); 4) I'd still like to see some kind of link to an updated FAQ or summary somewhere in the top level dropdowns, it certainly helped me get more comfortable with the project.  Cheers.

**Comment by jackalyst** [comment]
Thank you, can't do that without the excellent feedback you always seem to provide :+1: 

1. Academia has gotten a bit broad. Might be worth a thought to split it into two different headings
2. Could be kept to 'protocol updates' - but I think people generally are looking for what's ahead and it roadmap is the word people are used to. Need to think on this one as well, but 'protocol updates' does work quite well for that header.
3. Ah, 'external resources' does seem to describe that section well.
4. 'Getting started' is intended to help more directly than the FAQ, though wouldn't mind seeing FAQ returned under 'getting started'. It beefs up the site and I know I liked to use it to quickly reference topics. The other possibility is making the docs section more friendly by having it searchable in a similar way to FAQ, 'knowledge base' comes to mind as a more professional term too.

**Comment by jplomas** [comment]
Stale issue closed with site relaunch
