### ISSUE TITLE
Brand/website color scheme change

### ISSUE THREAD

**Issue by PQAdvantage** [theQRL/theqrl.org#75]
Can we please consider moving away from pink to a darker redder hue like Cap One (one of the fastest growing financial companies in the US) or dare I say a nice green, which connotes wealth and prestige (https://www.entrepreneur.com/article/175428)?  I'm not trying to be sexist, but I believe the significant majority of the crypto world are males who may have visceral negative reactions to it, and I don't think it inspires the kind of seriousness and security that this project warrants.  I know there are differing brand/marketing philosophies about the psychology of color and there are some potential positive associations for pink (https://www.fatrabbitcreative.com/blog/psychology-of-the-color-pink-and-what-it-means-for-your-business).  But I don't think it makes _any_ sense for QRL.  QRL isn't trying to inspire the same feelings as Victoria Secret or Barbie. T-Mobile is literally the only comparable type of company I can think of that embraces it as a main color and maybe it helps them stand out in a crowded field.  But I just don't think it works for QRL, which I view as having security as a fundamental value and focus which is not connoted by pink. Sorry this may seem like a trivial matter, but it bugs me everytime I see it and think it could have a longterm, important impact on the marketing efforts of the project.

**Comment by jackalyst** [comment]
Another great issue.

There is a lot of talk about color psychology, but I've found it to be an area fraught with beliefs more so than facts - and it's a dangerous thing to rely on. Countless blogs will confer with countless other blogs and it would all seem to be 'common sense', but it's also something so rarely questioned. If someone says that drinking coffee lets you live 5 years longer, you'd respond with "show me the evidence". But "cool blue is perceived as trustworthy, dependable, fiscally responsible and secure" goes uncontested.

Worth a read is [Color and psychological functioning: a review of theoretical and empirical work](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4383146/) which concludes:

> It is premature to offer any bold theoretical statements, definitive empirical pronouncements, or impassioned calls for application; rather, it is best to be patient and to humbly acknowledge that color psychology is a uniquely complex area of inquiry (Kuehni, 2012; Fairchild, 2013) that is only beginning to come into its own. Findings from color research can be provocative and media friendly, and the public (and the field as well) can be tempted to reach conclusions before the science is fully in place. There is considerable promise in research on color and psychological functioning, but considerably more theoretical and empirical work needs to be done before the full extent of this promise can be discerned and, hopefully, fulfilled.

With *that* out of the way, I do see a strong argument for changing the default color from pink to a blue variant being that you want to fit into similar brands that evoke the right emotion, and that if predominately males are looking at this, some might be absolutely repulsed, or at least reduce the enjoyment a lot.

We do have a blue in our colour guideline that fits:

![Screenshot from 2019-03-28 12-11-54](https://user-images.githubusercontent.com/232510/55182184-c4a7a500-5152-11e9-9f64-9b08b823b449.png)

**Comment by PQAdvantage** [comment]
Ahhh that's so much better IMHO.  I get you may want some contrast colors in certain contexts, but I for one yeah highly endorse using variants of blue where possible and then perhaps a more of a red, green or even purple hue for contrast. Thanks for considering.

**Comment by dzid26** [comment]
I think it would be better if the background was the signature purple - similar to what you ha e at the bottom.

**Comment by jackalyst** [comment]
Just tested a bit with signature purple, and I came up with this:
![Screenshot from 2019-07-09 09-09-38](https://user-images.githubusercontent.com/232510/60900527-8f1e5780-a229-11e9-8f41-0d4929500bca.png).

**Comment by atoma01** [comment]
"Just tested a bit with signature purple, and I came up with this:"

A little to dark maybe? Try turning down your screen backlight and the details disappear. I allway use minimum backlight to save my eyes. But i love dark themas.

**Comment by jplomas** [comment]
1. You could do a nice pulse between colours (e.g. as found here: https://css-tricks.com/almanac/properties/a/animation/ )

2. I think the options are starting to get cluttered and busy.  How about one big download button and a download page:
![image](https://user-images.githubusercontent.com/2139011/60903018-84cf7e00-a268-11e9-92fe-62a1273c7ee3.png)

**Comment by dzid26** [comment]
This is almost exaclty what I imagined on the mainpage when revisiting it after a while, (but to my surprise it was white -I think the white can be reserved for documentation. )

I guess my associations come from backrounds in places like that https://www.youtube.com/watch?v=3YxjMZGxm7A.  We probably want to keep the QRL image kept consistent. 

On the Samsung's OLED, I can see more color, but on PC it appears a bit dark and blueish. In my brain, the QRL backrounds are ever so slightly more purple.  But maybe that is due to pink text that gives that asscociation.  
In anycase, I like it what I see on the picture. Maybe you could run it through few other people to take an average opinion.

**Comment by jackalyst** [comment]
Maybe that's it. Increased the brightness a little bit. 
![Screenshot from 2019-07-09 09-39-12](https://user-images.githubusercontent.com/232510/60902817-82036780-a22d-11e9-9c58-a2b9ab423d04.png)

Not sure where I sit on the dark theme overall. I know I *prefer* the lighter theme, but if more people enjoy a darker theme/header and are more likely to stick around, I'm all for it. I don't think a toggle is necessary, and seems more applicable for applications than websites.

I agree things are getting a bit cluttered and a separate download page would be better to proliferate the download options/choices. The one benefit of having them all there is it can nicely demonstrate that we have everything covered.

Interesting thought on having things pulsing a bit, which can be seen with some of the particle images. I *do* think that having too much movement actually detracts from the content of the page and can otherwise pull a users attention away from other call to actions we may have.

**Comment by atoma01** [comment]
In regard to toggle feature. Please consider it. It good to have the choice and it does not need to be in your face. Just ad a small moon / half-moon in the upper right corner. Much like the bittrex website.

**Comment by dzid26** [comment]
The toggle wouldn't hurt. But this issue is more about the brand, not the practicality. 

The main page is where the **brand** is pushed to the new comers.  I have already associated qrl brand color with purple,.. but maybe it is white. Whatever the color is I believe it needs to be presented on the main page and carved in the people's brains. 

From the brand perspective - giving the toggle, may add a sense of "feeling at home", even if he never switches it. But it also may imply to the user, that this is an aplication site, as jackalyst said, which it is not, until one goes to wallet/block explorer.

**Comment by atoma01** [comment]
Ok, i see good point about the brand needing to be consistent.

**Comment by dzid26** [comment]
Looking at other brands with similar color schemes, that I know. Their website is not branded as much as the products they offer.  The websites are more traditional though, with focus on menus.
https://www.roku.com/
https://www.play.pl/en/oferta/play-karta/ (purple-white candy)

Though I think the dark background at this early stage of the QRL project would be appropriate.

**Comment by jplomas** [comment]
I'd support the theming of QRL web applications, but agree entirely with @dzid26 about the sanctity of the project ("brand") identity here.

**Comment by jplomas** [comment]
Stale issue closed with site relaunch
